version: '3.7'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/movie_db
    depends_on:
      - db
# remove the below volume before production
    # volumes:
    #   - ./api:/api

  db:
   image: postgres:latest
   environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_db
   volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: